version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "[%(asctime)s] [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: False

  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [default]
    level: INFO
    propagate: False

root:
  level: WARNING
  handlers: [default]
