CREATE DATABASE IF NOT EXISTS YoloHome;
USE YoloHome;

CREATE TABLE User (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    expo_push_token VARCHAR(255) NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Device (
    id CHAR(36) PRIMARY KEY,
    feed_id VARCHAR(255) UNIQUE NOT NULL,
    user_id CHAR(36) NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    min_value NUMERIC(10, 2) NOT NULL,
    max_value NUMERIC(10, 2) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE User_Log (
    id CHAR(36) PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    device_id CHAR(36) NOT NULL,
    action VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Sensor_Data (
    id CHAR(36) PRIMARY KEY,
    device_id CHAR(36) NOT NULL,
    value NUMERIC(10, 2) NOT NULL,
    alert BOOLEAN NOT NULL DEFAULT FALSE,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Status (
    id CHAR(36) PRIMARY KEY,
    device_id CHAR(36) NOT NULL,
    type ENUM('active', 'inactive', 'error', 'maintenance') NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Device 
ADD CONSTRAINT fk_device_user FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE;

ALTER TABLE User_Log 
ADD CONSTRAINT fk_userlog_user FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
ADD CONSTRAINT fk_userlog_device FOREIGN KEY (device_id) REFERENCES Device(id) ON DELETE CASCADE;

ALTER TABLE Sensor_Data 
ADD CONSTRAINT fk_sensor_device FOREIGN KEY (device_id) REFERENCES Device(id) ON DELETE CASCADE;

ALTER TABLE Status 
ADD CONSTRAINT fk_status_device FOREIGN KEY (device_id) REFERENCES Device(id) ON DELETE CASCADE;