CREATE DATABASE IF NOT EXISTS YoloHome;
USE YoloHome;

CREATE TABLE User (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE User_Log (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    action VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Device (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    min_value FLOAT NOT NULL,
    max_value FLOAT NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Sensor_Data (
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT,
    value FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Status (
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT,
    type ENUM('active', 'inactive', 'error', 'maintenance') NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Alert (
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT
);

ALTER TABLE User_Log 
ADD CONSTRAINT fk_userlog_user FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE;

ALTER TABLE Device 
ADD CONSTRAINT fk_device_user FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE;

ALTER TABLE Sensor_Data 
ADD CONSTRAINT fk_sensor_device FOREIGN KEY (device_id) REFERENCES Device(id) ON DELETE CASCADE;

ALTER TABLE Status 
ADD CONSTRAINT fk_status_device FOREIGN KEY (device_id) REFERENCES Device(id) ON DELETE CASCADE;

ALTER TABLE Alert 
ADD CONSTRAINT fk_alert_device FOREIGN KEY (device_id) REFERENCES Device(id) ON DELETE CASCADE;
